title: Maven Builder Pte Ltd
description: Construction with precision and integrity
theme: minima

header_pages:
  - about.md
  - services.md
  - projects.md
  - capabilities.md
  - homeowner-app.md
  - copilot.md
  - insight.md
  - lens.md
  - contact.md